version: '3.2'

services:
  app:
    build:
      context: application/
    container_name: application
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customers
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'library/postgres:latest'
    container_name: db
    environment:
      - POSTGRES_DB=customers
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password